brands =  [
    'SIN MARCA',
    'CHEVROLET',
    'DAEWOO',
    'FIAT',
    'KIA',
    'MAZDA',
    'RENAULT',
    'VOLKSWAGEN',
    'DODGE',
    'SIMCA',
    'PLYMOUTH',
    'OLDSMOBILE',
    'LANCIA',
    'NISSAN',
    'PEUGEOT',
    'SUBARU',
    'DATSUN',
    'BUICK',
    'CADILLAC',
    'HONDA',
    'BRONCO',
    'MITSUBISHI',
    'PONTIAC',
    'TOYOTA',
    'VOLVO',
    'ALFA ROMEO',
    'BMW',
    'FERRARI',
    'MERCEDES BENZ',
    'ROLLS ROYCE',
    'JAGUAR',
    'DACIA',
    'LADA',
    'OLTCIT',
    'TAVRIA',
    'VOLGA',
    'SKODA',
    'CITROEN',
    'DAIHATSU',
    'GAZ',
    'UAZ',
    'ARO',
    'MERCURY',
    'OPEL',
    'ISUZU',
    'JEEP',
    'LAND ROVER',
    'SUZUKI',
    'CHRYSLER',
    'FORD',
    'YAMAHA',
    'KAWASAKI',
    'HARLEY DAVIDSON',
    'AUTECO',
    'INTERNATIONAL',
    'ASIA MOTOR',
    'MACK',
    'CAGIVA',
    'WILLYS',
    'KENWORTH',
    'IVECO',
    'LAMBRETA',
    'MINSK',
    'HERO',
    'AUSTIN',
    'AUTOCAR',
    'DESOTO',
    'HINO',
    'DINA',
    'GEO',
    'DELTA',
    'HYOSUNG',
    'HUSQVARNA',
    'GMC',
    'VIASA',
    'KUBOTA',
    'TAM',
    'BELARUS',
    'JIALING',
    'ZASTAVA',
    'HUALI',
    'MONTESA',
    'FARGO',
    'ROVER',
    'CORCEL',
    'KAMAZ',
    'PUCH',
    'EBRO',
    'JINCHENG',
    'NASH',
    'WARTBURG',
    'MORRIS',
    'RAMBLER',
    'WILLCO',
    'QJIANG',
    'SISU',
    'SEAT',
    'ABARTH',
    'AUDI',
    'ASTON MARTIN',
    'AUTO UNION',
    'AVIA',
    'CHECKER',
    'BROCK WAY',
    'BORG WARD',
    'BENTLEY',
    'BUSSING',
    'BEDFORD',
    'BERLIET',
    'BARREIROS',
    'COMMER',
    'DKW',
    'EDSEL',
    'FORDSON',
    'FREIGHTLINER',
    'FAUN',
    'HOHOLDEN',
    'HILLMAN',
    'HUDSON',
    'IFA',
    'ISO',
    'KIAMASTER',
    'LAMBORGHINI',
    'LOTUS',
    'MAN',
    'MAGIRUS DEUTZ',
    'MOSKOVICH',
    'MURAVEY',
    'NECKAR',
    'PACKARD',
    'F.S.O.',
    'ALEKO',
    'AMERICAN MOTOR',
    'ROA',
    'BEIJING',
    'DERBY',
    'HENRY J',
    'HYUNDAI',
    'JAWA',
    'LEXUS',
    'MINICORD',
    'PEGASSO',
    'PORSCHE',
    'REO',
    'SCANIA',
    'SSANGYONG',
    'STUDEBAKER',
    'TRIUMPH',
    'WARZAMA',
    'PIAGGIO',
    'COLMOVE',
    'DAELIM',
    'JIANSHE',
    'YUGO',
    'HUMMER',
    'KTM',
    'BAJAJ',
    'POLONEZ',
    'BEISUTE',
    'XINGFU',
    'AGRALE',
    'PETERBILT',
    'DUCATI',
    'MG',
    'RAF',
    'SPARTAN',
    'PRINCE',
    'KINETIC',
    'BOMBARDIER',
    'INFINITI',
    'DAYANG',
    'ZUMY',
    'VAUSHALL',
    'VESPA',
    'B.S.A',
    'NORTON',
    'ITALJET',
    'VOSKHOD',
    'INDIAN',
    'GILERA',
    'MAHINDRA',
    'BABETA',
    'BULTACO',
    'BOCXOD',
    'CARABELLA',
    'MOTOGUZZI',
    'PACER',
    'PANNONIA',
    'PANHARD',
    'RONART',
    'SAMSUNG',
    'SANGLAS',
    'SUMBEAM',
    'SINGER',
    'SAVA',
    'TRABANT',
    'THAMES',
    'VOSJOD',
    'WHITE',
    'LML',
    'TATA',
    'SMART',
    'VARZI',
    'LIFAN',
    'KOREMOTO',
    'AKT',
    'SAIC CHERY',
    'DINLI',
    'GAS GAS',
    'CHANGAN',
    'OKLAN',
    'HAFEI',
    'LINHAI',
    'MAX MOTOR',
    'QINGQI',
    'GEELY',
    'CHANA',
    'CHERY',
    'SHENGQIBAO',
    'JEZHANG',
    'AYCO',
    'PIONEER',
    'SAIC WULING',
    'KINLON',
    'CHANGJIANG',
    'JET UKM',
    'AMC',
    'SIGMA',
    'MINI POCKET BIKE',
    'VICTORY',
    'CHANGHE',
    'LONCIN',
    'KAZUKI',
    'VENTO',
    'GOMOTOR',
    'XIALI',
    'TITANIA',
    'JINAN',
    'ACCURA',
    'HONLEI',
    'CPI',
    'BYD',
    'DUKAR',
    'SKYGO',
    'PASAGGIO',
    'KAYAK',
    'AUPACO',
    'MC MOTOR',
    'JIANGSU',
    'SACHS BIKES',
    'KYMCO',
    'MZ',
    'JUNESUN',
    'REAR',
    'WALTER',
    'KINROAD',
    'MORGAN',
    'HALLEY',
    'UKM',
    'ARIEL',
    'ATV',
    'WONJAN',
    'WANXIN',
    'JMSTAR',
    'ZONGSHEN',
    'BEST',
    'FUTONG',
    'YINGANG',
    'UNISON',
    'SKOOT MOTORCYCLES',
    'CHONGQING',
    'ARGO',
    'HUONNIAO',
    'KYOTO',
    'CMC',
    'URAL',
    'FIRENZE',
    'GREAT WALL',
    'GENESIS',
    'POLARIS ATV',
    'XISPA',
    'KEEWAY',
    'ZHEJIANG',
    'SUMOTO',
    'AUTOCAR WHITE',
    'KINROAD XINTIAN',
    'MOTOR UNO',
    'USW',
    'APRILIA',
    'RENNO',
    'GALARDI',
    'TYCO',
    'BUELL',
    'JONWAY',
    'JAC',
    'BORGO',
    'ZHONGXING',
    'U.S.W.MOTORS',
    'SYM',
    'ROYAL ENFIELD',
    'JOYNER',
    'AVANTI',
    'SANYA',
    'FOTON',
    'CNENLON',
    'YAMATI',
    'ROKETA',
    'ACCURO',
    'SHINERAY MOTOS',
    'UNITED MOTORS',
    'VENOM MOTORS',
    'TMEC',
    'QJ',
    'HAOJIN',
    'JBWCO',
    'SONGSHENG',
    'JMC',
    'VERUCCI',
    'BRITISH',
    'COBRA',
    'CUSHMA',
    'BUYANG',
    'GURGEL',
    'HUMBERT',
    'LA SALLE',
    'PIERCE ARROW',
    'PUMA',
    'SATURN',
    'WULING',
    'NITRO',
    'HAILI',
    'SAEHAN',
    'TONGKO',
    'FRIBEST',
    'NEW ERA',
    'BRP/CAN AM',
    'WEST',
    'XINGYUE',
    'VENTIE',
    'XL XINLING',
    'YUAN',
    'ACB',
    'HAMMER HEAD',
    'ZHEJIANG QIANJIANG',
    'ZHUJIANG',
    'POLARIS',
    'SCOOTER',
    'DFM',
    'YAKIMA',
    'MTK',
    'FASTER 301 CHOIPERS',
    'BOURGET',
    'REX MOTO',
    'HY MOTOR',
    'TVS',
    'HAOMEN',
    'ZHEJIANG LINGTIAN',
    'ZOTYE',
    'SUKYAMA',
    'CHANGFENG',
    'XINGUE',
    'KINGLONG HIGER',
    'KANDI',
    'BMA',
    'ATM',
    'MD BIKES',
    'WUYANG',
    'JINFENG',
    'PANTERA',
    'TERRA JET',
    'WCR',
    'KANCHAO',
    'FUXIANDA',
    'GWM',
    'RIDER',
    'ROSSETTI',
    'DONG FENG',
    'TIXXON',
    'ZNEN',
    'EKA MOTORS',
    'OROMOTO',
    'FAW',
    'SQ RACING',
    'ZAHAV',
    'YIBEN-YBFALCON',
    'ITALIKA',
    'AKITA',
    'BIG',
    'DAIFO',
    'EAGLE CARGO',
    'FUDEPAI',
    'GONOW',
    'GUZZI',
    'IOTA',
    'JIANG',
    'JIN JIN',
    'KYNLON',
    'MOTO MORINI',
    'NIKITA',
    'REBELLIN',
    'SHIJIAZHUANG',
    'TALON',
    'TELCOLINE',
    'TX MOTORS',
    'WORKMAN',
    'WUZHENG',
    'XINKAI',
    'A.J.S',
    'ACCESS',
    'ACE',
    'ACE MOTOR',
    'ACM-ZHONG',
    'ADDO',
    'ALLAD',
    'ALLIS CHALMERS',
    'ALPS',
    'AMM',
    'AMW',
    'AP PIAGGIO',
    'APELCO GEN-MTO',
    'ASTRA',
    'BACCIO',
    'BAODIAO',
    'BARBER GREENE',
    'BASHAN',
    'BAUKEMA',
    'BAW',
    'BETA',
    'BETTER',
    'BIANCHI',
    'BIMOTA',
    'BLAW KNOX',
    'BLUE STONE',
    'BOBCAT',
    'BODYWORK',
    'BONSER',
    'BOUSER',
    'BRIDGE',
    'BRONTO',
    'BUCYRUS',
    'BUGENI',
    'CAMECO',
    'CAN-AM',
    'CAPACITY',
    'CARIBE',
    'CARTER BROTHERS',
    'CASE',
    'CATERPILLAR',
    'CATFLYER',
    'CHAMPION',
    'CHANGLIN',
    'CHARLY',
    'CHARMING',
    'CHINSU',
    'CHONGQING ZONGSHEN',
    'CHONGQUING YUAN',
    'CICLONE USA',
    'CLARCK',
    'CLUB CAR',
    'COLOMBIANA DE CHASISES',
    'COMANDO',
    'COMET',
    'CONCORD',
    'CROWN',
    'CSEPEL-CUMMINS',
    'CUSTOM CHROME',
    'DAVID BROWN',
    'DAYUN',
    'DIAMOND',
    'DIECI',
    'DINAPAC',
    'DOMINGUEZ',
    'DRESSER',
    'DUST',
    'DYNACOLT',
    'E.D. ETNYRE',
    'EAGLE',
    'EAGLE AMC',
    'EASTMAN',
    'EBTELECTRIC',
    'ELECTRIC STAR ATV ENERGY',
    'ELGIN',
    'ENCAVA',
    'ENERGY',
    'ERNEST GRUBER',
    'EUCLID',
    'EVO',
    'EXCELSIOR',
    'EXPRESS',
    'EZLIFE',
    'FAILING',
    'FAMY',
    'FEDERAL',
    'FENCHI',
    'FIAT ALLIS',
    'FIORI',
    'FONA',
    'FORMULA',
    'FUTURE',
    'FWD',
    'FYM',
    'GALION',
    'GAZELLE',
    'GENERAL',
    'GHA-2',
    'GOLDEN DRAGON',
    'GRAM',
    'GROVE',
    'HARDLAND',
    'HARMON',
    'HELI',
    'HERRAGRO',
    'HILIGHT',
    'HISTER',
    'HITACHI',
    'HUBER',
    'HUMMER ZONGSHEN',
    'HYSTER',
    'INCALCU',
    'INDIAN CHIEF',
    'INGERSOLL RAND',
    'INVICTUS MOTORS',
    'JACKEL',
    'JAINSHE',
    'JAVELINI',
    'JCB',
    'JHON DEERE',
    'JHONSTON',
    'JIANG CHANGHE',
    'JIANGLING',
    'JIANGNAN GLOW',
    'JIANGSU KINROAD XINTIAN',
    'JIANGXI CAMPELL CO.',
    'JINGLONG',
    'JIRY SISU',
    'KAISER',
    'KALMAR',
    'KAZUMA',
    'KING LINFT',
    'KITOMI',
    'KOMATSU',
    'KONCEO',
    'KRAZ',
    'KRUPP',
    'LINCOLN',
    'LITTLE GIANT',
    'LIUGONG',
    'LMX',
    'LORAIN',
    'MADVAC',
    'MANCO',
    'MARMON',
    'MARUTI',
    'MASEY FERGUSON',
    'MATCHELSS',
    'MC CORMICK',
    'MERLO',
    'META',
    'MGB',
    'MINI',
    'MOTOBECAME',
    'MV AGUSTA',
    'NEW HOLLAN',
    'NEW KING',
    'NIMBUS',
    'NON PLUS ULTRA',
    'NUFFIELD',
    'OAKLAND',
    'OSHKOSH',
    'P Y H',
    'PARCE',
    'PETTIBONE',
    'PIAGGIO ZONGSHEN',
    'POCLAIN',
    'POWERMAX',
    'QIANJIANG',
    'RAMIREZ',
    'RANGE ROVER',
    'REVTECH',
    'RLX',
    'ROBUR',
    'ROSCO',
    'SAME',
    'SANFENG',
    'SAURON',
    'SHANGHAI',
    'SHINERAY',
    'SINOTRUK HOWO',
    'SKINGO',
    'SKYMAX',
    'SMC',
    'STEYR DAIMLER PUCH',
    'SUKIDA',
    'SUM',
    'SUNDIRO',
    'TCM',
    'TEREX',
    'THUNDER CYCLE DESIGN',
    'TONARO',
    'TRIWIL',
    'UNIMOG',
    'UNIVERSAL',
    'USA MOTORS',
    'VALMET',
    'VALTRA',
    'VISAIL',
    'VOGELE',
    'WARZAWA',
    'WESTERN STAR',
    'WKT',
    'XCMG',
    'YALE',
    'YAMASAKY',
    'YIBEN',
    'YONKANG XINGYUE',
    'YUANDA',
    'YUEJIN',
    'YUMBO',
    'ZEPHYR',
    'ZETOR',
    'ZHEJIANG HANGCHA',
    'ZHENG LI',
    'ZID',
    'ZIGMA',
    'ZIP STAR',
    'ZODIAC',
    'ZUNK',
    'CARBONER',
    'BUGGY',
    'CACIQUE',
    'RHINO',
    'BELL',
    'FURUKAWA',
    'ISEKI',
    'KATO',
    'KOBELCO',
    'LEE BOY',
    'LINK BELT',
    'MARINI',
    'MATBRO',
    'PANZER',
    'PINZ GAUER',
    'PIQUERSA',
    'TADANO',
    'CCITTA REBEL',
    'DELKRON',
    'DESTA',
    'JINBEI',
    'JINGPIN',
    'KAELBLE',
    'L.R.',
    'LIMA',
    'MOBILIFT',
    'OSSA',
    'PHW',
    'STAVOSTROJ',
    'TCUMSON',
    'TENNAN',
    'TOWMOTOR',
    'VERKHOVINA',
    'VOSJOB',
    'HORNET',
    'ZUNDAPP',
    'CZ',
    'DANUVIA',
    'CEZET',
    'GO KART',
    'MASERATI',
    'AC',
    'AG',
    'ALFARO',
    'ALVIS',
    'AMPHICAR',
    'AMPLE',
    'APOLLO',
    'ARABELLA',
    'ASPT',
    'AUTOKRAFT',
    'AYCO ZONGSHEN',
    'BAIKANCAR',
    'BAKER',
    'BANTAM',
    'BENELLI',
    'BOSA BOSHIE NIKE',
    'BRAND',
    'BRISA',
    'C.C.C.',
    'CAMC',
    'CENTAURS',
    'CHINA MOTORCYCLES',
    'CHITUMA',
    'CLAUSSON',
    'COLT LANCER',
    'CONSUL',
    'CROSLEY',
    'CRUISERN',
    'DACC',
    'DAF',
    'DAIMLER BENZ',
    'DASHA',
    'DE LA HAYE',
    'DEMAG',
    'DIVICO',
    'DTV',
    'ECO CITI',
    'EL SOL',
    'ELEPHANT POWER',
    'EM',
    'EP',
    'E-TON',
    'EZGO',
    'F.N',
    'FANTIC',
    'FARSPEED',
    'FIBRAVAN',
    'FLEXIBLE',
    'FRAZER',
    'FULDAMOBIL',
    'GERLING',
    'GOGOMOVIL',
    'GRAHAN PAUGE',
    'GRANE CARRIER',
    'GREMLIN',
    'GRUBER',
    'HALLA',
    'HAOJUE',
    'HESTIA',
    'HOSIN SOPORTER',
    'HUAWIN',
    'HUPMOBILE',
    'HUSABERG',
    'I.M.V',
    'IKARUS',
    'ISLO',
    'JIN JIAN',
    'JUMBO DE LLANTAS',
    'JUNGHEINRICH',
    'KANABIS',
    'KARPETAN',
    'KOMAR',
    'KONTIO SISO',
    'KROSON SOPORTES',
    'L.A.I',
    'LEE SCUSTÓN COACHES',
    'LEY LAND',
    'LIANMEI MOTOR',
    'LIBA MOTOR',
    'LINDE',
    'LINGBEN',
    'M.G.U',
    'MARCHETTI',
    'MARQUASS',
    'MASTER CRAFT',
    'MAXWELL',
    'MAYFLOWER',
    'MAZAKI',
    'MG MIDGET',
    'MNHCK',
    'MOBYLESTTE',
    'MONIKA',
    'MOTOCARRIER',
    'MUDAN',
    'MUHCK',
    'N.S.U',
    'NEUTRAL',
    'NEW HYSTER',
    'NYK',
    'ORANGE COUNTY CHOPPERS',
    'ORION',
    'PASSO',
    'PEXMA',
    'PLANETA',
    'POWER WAGON',
    'PREFECT',
    'RABBIT',
    'REVA',
    'ROSENBAUER',
    'SAAB',
    'SANDI',
    'SANGLIN',
    'SAURER',
    'SCAMMELL',
    'SEAGRAVE',
    'SERVAL',
    'SHANGLI',
    'SHANYANG',
    'SHERPA',
    'SHUANGHUAN',
    'SHUANGSHI',
    'SKYTEAM',
    'SOLARI',
    'SONIKA',
    'SONZINI',
    'SOYAT',
    'SP@ZZIO',
    'SRFHUAIGE',
    'SST',
    'STEINBOCK',
    'STIRES VM',
    'SUMO',
    'SUNASA QINGQI',
    'SUPERMOTO',
    'TALBOT',
    'TANTA',
    'TATRA',
    'TEMPO',
    'TGA-200-G',
    'TMD',
    'TONGYU',
    'TOYOPET',
    'TULA',
    'UFO',
    'VALIANT',
    'VALKYRIE',
    'VANGUARD',
    'VOGUE',
    'VONROAD',
    'WAGONNER',
    'WAJAX',
    'WINCHEMG',
    'WLLHELMSHAVEN',
    'WORD LA FRANCE',
    'WORLDSTAR',
    'WSK',
    'XINGLING',
    'XINLING',
    'XINTIAN KINROAD',
    'XSG ING QIJITUA',
    'YLM',
    'ZENA',
    'ZHAN',
    'ZHONGNENG',
    'ZHONGYU',
    'ZIU',
    'ZQ MOTORS',
    'ZUK',
    'ZUK NYSA',
    'ALL STATE',
    'ALLARD',
    'HONGXING NOBLE',
    'CIXI KONCEO',
    'HAOJIANG',
    'PRATOO Y FORNE',
    'REGAL RAPTOR',
    'WEST WARRIOR',
    'AEOLUS',
    'AUTO BIANCHI',
    'BAW ZHAN QI',
    'FODEN',
    'IFG',
    'JINLING',
    'LLOYD',
    'LUAZ',
    'PANDA CHUNZOHN',
    'PAZ',
    'ROCAR',
    'ROMAN',
    'SCOUTY',
    'SKANIA VABIF',
    'SSANGYANG',
    'STAR',
    'STUTZ',
    'T.J.C.',
    'TANDEM',
    'TONGBAO',
    'TRADER',
    'UNDERBONE',
    'VEDETTE',
    'VOSHUD',
    'YITAKI',
    'ZHONGHUA',
    'STERLING',
    'THOMAS',
    'BOMAG',
    'SANY',
    'AUTECO BAJAJ',
    'AUTECO KYMCO',
    'DRESSER HAULPAK',
    'MAZ',
    'MOXI',
    'PERLINI',
    'HOREX',
    'LIEBHERR',
    'FIVER',
    'YUTONG',
    'WANHU',
    'MALAGUTI',
    'ARCTIC CAT',
    'DCEC',
    'TOURING',
    'HIGER',
    'MGU',
    'CFMOTO',
    'TEMPEST',
    'FUXIN',
    'XRP SAIN',
    'HENSIM',
    'SANLEE',
    'AUTECO VICTORY',
    'TEAM RYDER',
    'HUALIN',
    'SHACMAN',
    'BOUE',
    'AVA MOTORS',
    'SUMA',
    'SM',
    'BARHOG/DADYW',
    'MOTOKART',
    'MANZINI',
    'YONGKANG EASY VEHICLE',
    'MITSUBISHI FUSO',
    'ISHIMOTO',
    'ASA',
    'ESSEX',
    'KHOOBRA',
    'YAKEY',
    'GREENWHEEL',
    'TORNADO',
    'HAIMA',
    'SMA',
    'VOLDA',
    'HISUN TIGER',
    'TRACTOCASA',
    'AWS - ALIEN WORK SHOP',
    'JIANGSU SINSKI',
    'LINGKEN',
    'YGM',
    'WANCH',
    'TAO TAO',
    'GALAXI',
    'PACIFIC',
    'BYVIN',
    'JIASHITE',
    'ENERGY MOTION',
    'HPOWER',
    'YADEA',
    'JLC',
    'ADVANCE',
    'JIAJUE',
    'ETX',
    'JBC',
    'DFA',
    'E-ONE',
    'DETROIT',
    'KMO',
    'HUNTER',
    'THOMAS BUILT BUSES',
    'LOVOL',
    'D LONG',
    'TAYLOR DUNN',
    'HAORI',
    'SHELBY',
    'VMOTO',
    'CARPATI',
    'LUCKY LION',
    'CLC MOTOR',
    'MAHINDRA DURO',
    'BENLING',
    'OULING',
    'YAXING',
    'HANLING',
    'ZNA',
    'HUANGHAI',
    'DADI',
    'KING LONG',
    'ESCORPIO',
    'DFSK',
    'OLIYA',
    'GSMOON',
    'BERA',
    'XGJAO',
    'SENKE',
    'LANGQING',
    'AWS',
    'HONOR',
    'JAUNCE',
    'ZILI MOTORS',
    'ALFA',
    'ASIA HERO',
    'SINOTRUK',
    'POLARSUN',
    'UD TRUCKS',
    'JUNCHI',
    'SELVAXTREMA',
    'MOFFETT',
    'FASTER',
    'MIKILON',
    'SANYOU',
    'GAME',
    'FENIX',
    'INDUSTRY',
    'GBMCO',
    'GVMCO',
    'HSUN',
    'T-KING',
    'SEIKI',
    'HEIL TRAILER INTERNATIONAL',
    'PPM',
    'PAILISON',
    'ROAD SPORT',
    'ZOOMLION',
    'JINLUN',
    'RENLI',
    'SHERCO',
    'HARRIS',
    'AGUILA',
    'HIOSUNG',
    'MIGARGI',
    'WINDAR',
    'SHIFENG',
    'E- MAX',
    'HERSA',
    'SULTANA',
    'CARTER',
    'EMPIRE',
    'VDL',
    'CNJ',
    'TAYRONA',
    'SHAANQI',
    'RG',
    'TARANTULA',
    'UPBEAT MOTOR',
    'JEREH',
    'CHALLENGER LOWBOY',
    'MOTOABC',
    'BLUE BIRD',
    'GREENTRANS',
    'SHANDONG',
    'MODASA',
    'RTM',
    'CVT RATO',
    'ATV RATO',
    'KAMAJI',
    'FOSHAN CITYFOSTI',
    'HME',
    'S/M FAB',
    'DANDONG HUANGHAI',
    'ZONDA SOL',
    'KING STEYR',
    'HYDUKE',
    'BON LUCK',
    'AM GENERAL',
    'SHENKE',
    'BEI BEN',
    'FRANKS',
    'SIMON DUPLEX',
    'KAXAMOTOS',
    'CAN AM BOMBARDIER',
    'FEIZHEN',
    'VAISAND',
    'DFAC-DONG FENG',
    'FAUN/TADANO',
    'LLOCATELI',
    'STRONG',
    'IDECO',
    'BUCEGI',
    'HAI XING',
    'WOLSELEY',
    'HUASHA',
    'SHENLI',
    'LINYU',
    'HONGOI',
    'ZERO',
    'CIBER',
    'RATO',
    'KW-B800',
    'UNICO',
    'BAIBEN TRUCK',
    'ANIVER',
    'LANDINI',
    'TOPTOM',
    'RIEJU',
    'IVECO MAGIRUS',
    'LINTEX',
    'BERING',
    'BRILLIANCE',
    'YONGKANG',
    'LIANGZI',
    'TONGHUA',
    'TAYLOR INDUSTRIES',
    'YOUNGMAN',
    'LIZHONG',
    'AMERICAN LA FRANCE',
    'PEMFAB',
    'KING ROAD',
    'JUPITER',
    'ESCUTER',
    'WHITE WESTERN',
    'ECO JAMCHA',
    'RIYA MOTORA',
    'IVECO FIAT',
    'JOYLONG',
    'HARDKNOCK',
    'SPYDER',
    'FEISHEN',
    'TENNANT',
    'GREEN',
    'SAN JI',
    'THUMB',
    'ZHONGPONG',
    'NAVISTAR',
    'SI JI',
    'ZHONGTONG',
    'IPV',
    'DEYI',
    'HONOR-QJ',
    'AN YUAN',
    'S&C',
    'JINLING TIGERS',
    'TIGER',
    'GOLOEN LEOPARO',
    'FULU',
    'CHENGLONG',
    'EV TECH JAPAN',
    'WYS',
    'HM HONDA',
    'GOES',
    'XINYUE',
    'VECTRIX',
    'SUPERFORMANCE',
    'FENGCHI',
    'SHA TUO',
    'MAXUS',
    'DONGBEN',
    'LVTONG',
    'ATV RACING',
    'ULTIMA',
    'DONG-A',
    'KOEHRING',
    'TIANMA',
    'KAMA',
    'RAINCHST',
    'DBO',
    'V-WINGS',
    'VICMARS',
    'NBLUCK',
    'HUANSONG',
    'TL',
    'SKYNGO',
    'GRUMMAN',
    'ACURA',
    'TESUO',
    'YUAMDA',
    'SUNRA',
    'MAKIBA',
    'LIATONG',
    'BSA',
    'CABOT',
    'COMMUTER',
    'COOPER',
    'KATANA',
    'LOADCRAFT',
    'TITAN',
    'WEAPON GENERAL',
    'WILSON',
    'ZIMMER',
    'XIANFENG',
    'WRIGHTBUS',
    'BELKOMMUNMASH',
    'FALCON',
    'RANDON',
    'TYTAL',
    'CAN-AM OUTLANDER',
    'HEXAGON LINCOLN',
    'STANDARD',
    'SKYMOTO',
    'JMCOMPETETIOM',
    'FAW-HONGQI',
    'GOLIATH',
    'STANDARD TRIUMPH',
    'JC',
    'CANAM',
    'UM',
    'KHD DEUNZ',
    'DIAMONTH',
    'SUPER',
    'I H C PAYSTAR',
    'SAIC',
    'TIGER POWER',
    'LA CANE',
    'HC',
    'YUEHAO',
    'ATK',
    'SANTANA',
    'FTF',
    'PITSTER PRO',
    'FMC WAYNE',
    'SAETA',
    'MD BASHAN',
    'WARRIOR ROAD',
    'ARES',
    'THAMES TRADER',
    'TAILG',
    'DURATI',
    'ILLUSION',
    'ZEASY',
    'GOGOMOBIL',
    'ZANELLA',
    'TAIHENG',
    'MINICHOPPER',
    'YONGKANG JINLING',
    'TARANTULA HUABAD',
    'ROMARCO',
    'GREAT DANE',
    'ZONSHEN',
    'TAUNUS',
    'CAETANO',
    'KINGTON',
    'BAIC',
    'LANDWIND',
    'HONGYAN',
    'BRAMMO',
    'DONGFENG',
    'SPRIENTER FREIGHTLINER',
    'SLANE',
    'BAOYA',
    'BRAMMO IMPULSE R.',
    'GREEN THOR',
    'HECHI TOOLS',
    'MOTO GUZZI',
    'LONDON  MACHINERY',
    'DI BLASI',
    'DFLZ',
    'SUNNY',
    'BEIBEN',
    'FINE CENTURY CO LTD',
    'FOLARIS',
    'CYCLER',
    'DSFK',
    'NISSAN CABSTAR',
    'MOTO ABC',
    'WERDEAU',
    'EAGLE TALON',
    'CHOPPER',
    'INTERNATIONAL F9370',
    'SINOTRUKHOVA',
    'COLES CRANES',
    'SJ.PETRO',
    'GOVECS',
    'BENDA',
    'ZSPEM',
    'JEEPSTER VIASA',
    'DACIA 10',
    'JIANGSU JINJIE',
    'XINYANG',
    'SSTERLING',
    'NORTH BENZ',
    'NISSAN PATROL',
    'GREEN SAVER',
    'LUYUAN',
    'BOSS ATV',
    'YCF',
    'DUNE BUGGYS',
    'TM RACING',
    'MOZ',
    'QISHENG',
    'YINXIANG',
    'MERCEDES BENZ/UNIMOG',
    'TELDIUX',
    'NAVECO-IVECO',
    'SINSKI',
    'ELEKTRA',
    'GARELLI',
    'ARTIC CAT',
    'RAVO',
    'JOHN DEERE',
    'BRICKLIN',
    'MORINI',
    'CAN AM',
    'WHITE MOTORCORPORATION',
    'EONE HURRICANE',
    'HTA',
    'JBC JINBEI',
    'CANCE CASHSUYE',
    'AUSA',
    'X-TRON POWER ENERGY',
    'MCLAREN',
    'USW MOTORS',
    'NEW HOLLAND',
    'FORLAND',
    'ACURA INTEGRA',
    'FEIYING',
    'INDUSTRIAS MORENO',
    'MH KN2',
    'MH RACING',
    'MH7 NAKED',
    'PEGASO',
    'SHANGYANG',
    'FORD LAND',
    'UROMAC',
    'E-MOTORI',
    'EP-EP',
    'C.O.C.',
    'WELLUCK',
    'TRIUMPH MOTORCYCLES',
    'VENICE',
    'AIMA',
    'APRIL EV',
    'DERBI',
    'SLNG',
    'MAVILA',
    'PIERCE',
    'SANLG',
    'FORCE',
    'LARETTO',
    'JEEP WRANGLER 4WD',
    'KAMAX',
    'SUNWIN',
    'ZONLON',
    'TAYLOR',
    'BECEMA',
    'VOLVO BM',
    'MGA',
    'ERSKINE',
    'TM',
    'SCHWARSE SUPERVAC',
    'SHANDONG XINDAYANG',
    'AUBURN',
    'GATOR',
    'BOSS',
    'PRAKLA',
    'ELEKTROMOTORES',
    'PRECISION CYCLE WORKS',
    'ELEXTROMOTORES',
    'MARCOPOLO',
    'DEUTZ',
    'GENOVO POWER',
    'FUSO',
    'GARWOOD',
    'BLAWKNOX',
    'CHAOWEI',
    'NAVISTAR INTERNACIONAL',
    'YUEJIN - NAVECO',
    'H14.00XM',
    'RANGER CREW 900',
    'SUNLONG',
    'IASA',
    'BK MOTO',
    'KAP',
    'FUXIN-F-FX',
    'TOYOTA SCION',
    'AVENGER',
    'RING SIMONS',
    'SANLING',
    'KIKKER 5150',
    'RARIRO',
    'CAMPAGNA',
    'TRUMPCHI',
    'GOUPIL',
    'AUTOBIANCHI',
    'LYNGYUN',
    'MH MOTOCYCLES',
    'BAOTIAN',
    'KING MOTOR',
    'NISSAN URVAN',
    'CHAMPION PERFORMANCE',
    'PIAGIO',
    'MG MORRIS GARAGES',
    'NATSUKI',
    'KAISER JEEP CORPORATION',
    'MITSUBISHI MONTERO',
    'WESTFIELD',
    'REVOLUTION 250',
    'GLOBAL',
    'A.C.F.',
    'PULLMAN',
    'DFAC',
    'U.D.M.',
    'MURRELL',
    'CATERHAM',
    'ZAGA',
    'BAIC/KENBO',
    'MESSERSCHMITT',
    'BECK',
    'ASIA MOTORS',
    'FAI',
    'PCC EU',
    'VOLTA',
    'KAMPERX',
    'CRANE CARRIER',
    'CHANGANG',
    'INMINES',
    'STÄRKER',
    'QILING',
    'ZHANG',
    'FERRARA',
    'YINJI',
    'TEREX BENFORD',
    'KAYSER',
    'LIL PICK UP',
    'HISUN',
    'NAVECO',
    'BMY',
    'WACKER',
    'KOMATSU FG25',
    'TX MOTOR',
    'ENDURO',
    'MOSRITO',
    'CAN AM BRP',
    'SCOOTER ROKETA',
    'STRADA',
    'KTX',
    'DS',
    'AMERICAN MOTOR JEEP',
    'EGO CAMBUCO',
    'HENDRICKSON',
    'SATURN SPORAGE',
    'MERCURI',
    'PLYMOUT',
    'CAN-AM BRP BOMBARDIER',
    'JIANSCHI',
    'ATOM',
    'SUSUKI',
    'AVA FENIX',
    'HARWAN',
    'SONLINK',
    'MOLTOVELUCE HARWAN',
    'SUNSHINE',
    'ANDES RZ',
    'TIANDA',
    'JPETRO',
    'SCOMADI',
    'CITIESX',
    'ANDES',
    'MACK TRUCKS',
    'TRI RING',
    'QIJING',
    'X-ZHANJING',
    'JEC',
    'BADER',
    'ZHENGLI',
    'TYM',
    'FANGXIN',
    'LANDER',
    'TOYOTA LAND CRUISER',
    'LONG CING',
    'ARO CARPATI',
    'SLINGSHOT',
    'LIZARD MOTORS',
    'WINNER',
    'CARABELA',
    'CARTER TALON',
    'RABA-MAN',
    'EV//NM SPORT//AA',
    'KENBO',
    'KTM.',
    '.KTM.',
    'CARDA',
    'CARMIX',
    'STARKER',
    'ABC',
    'MACBOR',
    'NISSAN-TIIDA',
    'SPORT POWER NEW/ELECTRIKA',
    'KROMHOUT',
    'NISSAN SENTRA',
    'ELECTRIC E-BIKE GX',
    'ELECTRIKA',
    'AUSTIN HEALEY',
    'ROSENBAUER AMERICA',
    'FREIGHT LINER',
    'ANKAI',
    'BIBREX',
    'BIGREX',
    'QUINGGQI',
    'YONGHE',
    'INTERNATIONAL EAGLE',
    'NATIONAL FOAM',
    'GEO METRO',
    'AUDI Q5',
    'TRAILMASTER',
    'AVA',
    'PRAVA',
    'KAWEIAUTO',
    'BESTA',
    'CAZADOR',
    'GOMOTORS',
    'SHJ',
    'BREMACH',
    'DAIAHTSU',
    'HANBIRD',
    'GREAT WALL-GWM DEER',
    'RAY DESF',
    'RONCO',
    'BRASELIO',
    'RAM',
    'KENWORD FODEN',
    'TOMOS REVIYAL',
    'POLSKI FIAT',
    'MAICO',
    'KTK',
    'IZHMASH',
    'JLP-LUNA',
    'SITOM',
    'MC MOTOS',
    'UNITEC USA',
    'SINOPEC',
    'PLUTUS SG',
    'TEXTRON',
    'GRUPO PEGASSO',
    'GUTBROD',
    'VERUCCI AVANTI',
    'BIRO',
    'BMS 552',
    'VACTOR',
    'LUNA',
    'CARGO EAGLE',
    'AUTECO/ROA',
    'RIGO',
    'SOUTH EAST',
    'TYMCO',
    'GEM',
    'DEVIN ERMINI',
    'EVERBRIGHT',
    'FOTON AUMAN',
    'BOSS-ATV',
    'ROBETA',
    'MAGIRUS',
    'P&H',
    'NIU',
    'LAVERDA',
    'EMPIRE KEEWAY',
    'DINGBA',
    'REEN TOUR PEACE - GTP',
    'GREEN TOUR PEACE - GTP',
    'ARO CORCEL',
    'INFINITIVE',
    'WINLEE',
    'ANAIG',
    'SWM',
    'AM GENERAL LLC',
    'KANGD',
    'LIANKE',
    'AGA',
    'CZ CAGIVA',
    'STARK',
    'FISCA',
    'ZHONGYOU',
    'HUAIHAI',
    'SKOOT',
    'X-EIHEI',
    'TESLA',
    'MINI COOPER',
    'BACKROAD CHOPPERS',
    'HK SHANSU',
    'ALTA MOTORS',
    'DAIX',
    'NOMADA´S ECO MOTO',
    'MAX MIKU',
    'WANSHAN',
    'JOHNSTON SWEEPERS',
    'AMERICAN LAFRANCE',
    'TORO',
    'PRATOO & FORNE',
    'XINLIBA',
    'AMMANN',
    'BIN',
    'EONE CYCLONE',
    'ZP',
    'SUTPHEN',
    'MERCEDES BENZ / IDEROL',
    'YONGFU',
    'EVOLUTION',
    'BENLG',
    'JIAYUAN',
    'MINGHONG',
    'ASIA',
    'ECO BRYSER',
    'PRAGA',
    'QSMOTOR',
    'ROSEWOOD',
    'SHENG',
    'KARRY',
    'LIGHTER',
    'MARSHELL',
    'ZHIDOU',
    'MISHOUZUKI',
    'CHAOW POWER',
    'CELERAK INK',
    'SHEKA /YARDY',
    'MAGIRUZ DEUTZ',
    'E2-GO',
    'CARPATY',
    'VESPACAR',
    'EZ-GO',
    'CDI SKYGO',
    'CIRCULA VERDE',
    'CAMELLO',
    'CONFEDERATE',
    'HARLEY-DAVIDSON',
    'CHANG JIANG',
    'ZONGQING',
    'NISSAN QASHQAI',
    'TRACKING',
    'NISSAN PATHFINDER',
    'SCHOPF',
    'NISSAN/QASHQAI',
    'GBM MOTORS',
    'MINGTO',
    'T.L. SMITH',
    'KINGBON JINPENG',
    'AUTECO KAWASAKI',
    'CERONTE',
    'TODAY SUNSHINE',
    'HARLEY',
    'JIANGSU LVNENG',
    'ANDINO',
    'HL TRAYKER',
    'COMBAT',
    'SHENYING',
    'NISSAN/TIIDA',
    'MOBIMAX',
    'NISSAN/D22',
    'BRYSER',
    'ORANSH',
    'SINOTRUK SITRAK',
    'TAO MOTOR',
    'QINGQI BRAND',
    'YAMAHA MAXIM',
    'ISOTHERMOS',
    'JUPITER-2',
    'WARSZAWA',
    'DAIHATSU - ROCKY',
    'BORGWARD',
    'HUMBER PULLMAN',
    'SUN BEAM',
    'PLR',
    'CUSHMAN',
    'MOSTKVICK',
    'HUMBER CEPTRE',
    'ROMEO-2',
    'ZXMCO',
    'MOSCVITCH',
    'MITSUBISCHI',
    'AMERICAN MOTORS',
    'KAWA',
    'KINGBON',
    'CHEVROLET-ALTEC',
    'NISSAN PRIMERA',
    'ZEDRIV',
    'MAXIUM',
    'QIANG SHENG',
    'CHIEB',
    'YMDY',
    'KAINING',
    'ELECTRIBIKE',
    'MILG',
    'ARO-CARPATI',
    'LINZDA',
    'NISSAN SUNNY',
    'LAND ROVER SANTANA',
    'DELOREAN',
    'YIJIE',
    'NYPABEU',
    'SMALLAND NICE',
    'CARMOTOS',
    'TOYOTA LAND CRUISSER',
    'NISSAN MICRA',
    'SAXON',
    'NISSAN ALMERA',
    'ZENG',
    'MOTOR CAFÉ',
    'ZONTES',
    'GUYUE',
    'DORCEN',
    'HORWIN',
    'HARLEY DAVISON',
    'NISSAN PATFHINDER',
    'LEITING HUANG',
    'NISSAN/SENTRA',
    'SONGI',
    'SUP',
    'NINEBOT',
    'BRENSON',
    'HOZON',
    'MOTOR CAFE',
    'MOTORCAFE',
    'NISSAN DIESEL',
    'AMERICAN COACH',
    'MERCEDES-BENZ',
    'NETA',
    'NO TIENE',
    'GENERAL MOTORS CORPORATION',
    'KIA BESTA',
    'BAOJUN',
    'SEYOUN NJK',
    'YAN HUI',
    'GAIA',
    'MOTO ELECTRIC VEHICLES',
    'NISSAN BLUEBIRD',
    'TAO',
    'TAOI',
    'SAIGE',
    'SULONG',
    'YUKI TOURS',
    'MOTOLIFE',
    'SUPER SOCO',
    'F.M.',
    'RTZ',
    'FTD',
    'NISSAN BLUEBRID',
    'NISSAN/NAVARA',
    'KW DART',
    'NISSAN/PATHFINDER',
    'HAWTAI MOTOR',
    'CHAOYA',
    'MINI COOPER S COUNTRYMAN',
    'YAMAAHA',
    'MERCEDDES BENZ',
    'FRATELLI',
    'NISSAN/X-TRAIL',
    'TYCO SCOOTER',
    'RICH 6',
    'TRAIL-BLAZER',
    '313 - BYD',
    'TOYOTA  HI-LUX',
    'TOYOTA HI-LUX',
    'BINTELLI',
    'TRACTOCAZA',
    'TOYOTA HIACE',
    'ACB MOTOS',
    'CHEVROLET GMC',
    'ACCUMOS',
    'JSA',
    'FLEEK',
    'NISSAN-ALMERA',
    'TAIAN WU YUE',
    'JINGPENG ECO1',
    'KING MOTOR/ QINGQI',
    'BIUCK SPECIAL',
    'LINCOLN CONTINENTAL',
    'SEGWAY',
    'AUTECO-ROA',
    'NISSAN/ALMERA',
    'WARTBURG',
    'JAVELIN',
    'LONGZU STAR',
    'NISSAN TERRANO',
    'BIOLOGICA',
    'CARPATI-ARO',
    'HQV',
    'GUNG',
    'UGBEST',
    'LINGSTAR',
    'WOLF',
    'NISSAN D/22',
    'NISSAN/ALTIMA',
    'APOLLO RXF',
    'PORSHE',
    'NISSAN-PRIMERA',
    'NISSAN/D21',
    'CHEVROLET LUV',
    'TOYOTA LAND CRUISER HARDTOP',
    'CAN-AM BOMBARDIER BRP',
    'BRP/CAN-AM',
    'NISSAN/MURANO',
    'SURRON',
    'EURISE',
    'THUNDER EV',
    'JINPENG',
    'XWD - XINGWANGDA/ YANTAI XINGYE MACHINERY',
    'NISSAN-VANETTE',
    'NISSAN X-TRAIL',
    'FORD INGLES',
    'CUATRIMOTO SAETA RINO 4X4',
    'POWER ELECTRIC',
    'E-RACE',
    'CUPRA',
    'WUYUE',
    'BRP/CAM-AM',
    'HUATAI / GBM MOTORS',
    '(DONGFENG MOTOR) / GBM MOTORS',
    'ADTEV',
    'TINBOT',
    'LVNENG',
    'ZHIGAO',
    'FORD GRANADA',
    'FREDLAINE',
    'ECOFLY',
    'COMMAND CARR',
    'NISSAN-PATHFINDER',
    'NISSAN PAHFINDER',
    'LONKING',
    'BAM',
    'ZONTVIK',
    'MBI',
    'CAN–AM',
    'CHEROKEE',
    'WILLIS',
    'ATUL AUTO LIMITED',
    'JINMA',
    'GRIS SILVERSTONE - NEGRO VULCANO',
    'ROJO MONTE CARLO - NEGRO VULCANO',
    'TADANO FAUN',
    'BOURGET´S BIKE WORKS',
    'FORD MUSTANG',
    'WHITE-AUTOCAR',
    'KAINUO',
    'MONARK',
    'VOGEPRO',
    'HENGNIU',
    'HIPERFECT',
    'MOTO GUZZI',
    'TADANO-FAUN',
    'ZCPC',
    'JETOUR',
    'ECOMI',
    'DODGE BROTHERS',
    'DNEPR-16',
    'HIGHPER',
    'QINGLING',
    'AUTECO KAWASAKI',
    'IONIC MOTORS',
    'HAIBAO'

]

classes = [
            "AUTOMOVIL",
            "BUS",
            "BUSETA",
            "CAMION",
            "CAMIONETA",
            "CAMPERO",
            "MICROBUS",
            "TRACTOCAMION",
            "MOTOCICLETA",
            "MOTOCARRO",
            "MOTOTRICICLO",
            "CUATRIMOTO",
            "REMOLQUE",
            "SEMIREMOLQUE",
            "VOLQUETA",
            "SIN CLASE",
            "MAQ.CONSTRUCCION O MINERA",
            "CICLOMOTOR",
            "TRICIMOTO",
            "CUADRICICLO"
        ]

models = [
'1900',
'1901',
'1902',
'1903',
'1904',
'1905',
'1906',
'1907',
'1908',
'1909',
'1910',
'1911',
'1912',
'1913',
'1914',
'1915',
'1916',
'1917',
'1918',
'1919',
'1920',
'1921',
'1922',
'1923',
'1924',
'1925',
'1926',
'1927',
'1928',
'1929',
'1930',
'1931',
'1932',
'1933',
'1934',
'1935',
'1936',
'1937',
'1938',
'1939',
'1940',
'1941',
'1942',
'1943',
'1944',
'1945',
'1946',
'1947',
'1948',
'1949',
'1950',
'1951',
'1952',
'1953',
'1954',
'1955',
'1956',
'1957',
'1958',
'1959',
'1960',
'1961',
'1962',
'1963',
'1964',
'1965',
'1966',
'1967',
'1968',
'1969',
'1970',
'1971',
'1972',
'1973',
'1974',
'1975',
'1976',
'1977',
'1978',
'1979',
'1980',
'1981',
'1982',
'1983',
'1984',
'1985',
'1986',
'1987',
'1988',
'1989',
'1990',
'1991',
'1992',
'1993',
'1994',
'1995',
'1996',
'1997',
'1998',
'1999',
'2000',
'2001',
'2002',
'2003',
'2004',
'2005',
'2006',
'2007',
'2008',
'2009',
'2010',
'2011',
'2012',
'2013',
'2014',
'2015',
'2016',
'2017',
'2018',
'2019',
'2020',
'2021',
'2022',
'2023',
'2024',
'2025',
'2026',
'2027',
'2028',
'2029',
'2030',
'2031',
'2032',
'2033',
'2034',
'2035',
'2036',
'2037',
'2038',
'2039',
'2040',
'2041',
'2042',
'2043',
'2044',
'2045',
'2046',
'2047',
'2048',
'2049',
'2050',
'2051',
'2052',
'2053',
'2054',
'2055',
'2056',
'2057'
]

colors = [
    "NEGRO",
    "AZUL",
    "MARRON",
    "CAFE",
    "GRIS",
    "VERDE",
    "NARANJA",
    "ROSA",
    "PURPURA",
    "ROJO",
    "BLANCO",
    "AMARILLO",
    "TURQUESA",
    "OLIVA",
    "MENTA",
    "BORGONA",
    "LAVANDA",
    "MAGENTA",
    "SALMON",
    "CIAN",
    "BEIGE",
    "ROSADO",
    "OLIVA",
    "LILA",
    "FUCSIA",
    "MOSTAZA",
    "OCRE",
    "TRULLO",
    "MALVA",
    "PURPURA"
    "OSCURO",
    "CIRUELA",
    "AZUL",
    "CLARO",
    "MELOCOTON",
    "VIOLETA",
    "GRANATE"
]