# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTGraphicInterfaces/CompactInterface.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(409, 860)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbr_load_image = QtWidgets.QGroupBox(self.centralwidget)
        self.gbr_load_image.setGeometry(QtCore.QRect(10, 10, 391, 111))
        self.gbr_load_image.setObjectName("gbr_load_image")
        self.btn_load_image = QtWidgets.QPushButton(self.gbr_load_image)
        self.btn_load_image.setGeometry(QtCore.QRect(10, 30, 371, 23))
        self.btn_load_image.setObjectName("btn_load_image")
        self.lbl_load_image = QtWidgets.QLabel(self.gbr_load_image)
        self.lbl_load_image.setGeometry(QtCore.QRect(10, 60, 371, 41))
        self.lbl_load_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_load_image.setObjectName("lbl_load_image")
        self.da_group = QtWidgets.QGroupBox(self.centralwidget)
        self.da_group.setGeometry(QtCore.QRect(10, 460, 391, 81))
        self.da_group.setObjectName("da_group")
        self.da_btn_clear = QtWidgets.QPushButton(self.da_group)
        self.da_btn_clear.setGeometry(QtCore.QRect(300, 30, 40, 40))
        self.da_btn_clear.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_clear.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_clear.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/limpiar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_clear.setIcon(icon)
        self.da_btn_clear.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_clear.setObjectName("da_btn_clear")
        self.da_btn_coordinates = QtWidgets.QPushButton(self.da_group)
        self.da_btn_coordinates.setGeometry(QtCore.QRect(90, 30, 40, 40))
        self.da_btn_coordinates.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_coordinates.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_coordinates.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.da_btn_coordinates.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/coordenadas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_coordinates.setIcon(icon1)
        self.da_btn_coordinates.setIconSize(QtCore.QSize(36, 36))
        self.da_btn_coordinates.setObjectName("da_btn_coordinates")
        self.da_btn_view = QtWidgets.QPushButton(self.da_group)
        self.da_btn_view.setGeometry(QtCore.QRect(260, 30, 40, 40))
        self.da_btn_view.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_view.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_view.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/ver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_view.setIcon(icon2)
        self.da_btn_view.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_view.setObjectName("da_btn_view")
        self.da_btn_delete = QtWidgets.QPushButton(self.da_group)
        self.da_btn_delete.setGeometry(QtCore.QRect(340, 30, 40, 40))
        self.da_btn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_delete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/eliminar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_delete.setIcon(icon3)
        self.da_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_delete.setObjectName("da_btn_delete")
        self.da_btn_color = QtWidgets.QPushButton(self.da_group)
        self.da_btn_color.setGeometry(QtCore.QRect(10, 30, 40, 40))
        self.da_btn_color.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_color.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_color.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.da_btn_color.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_color.setIcon(icon4)
        self.da_btn_color.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_color.setObjectName("da_btn_color")
        self.da_lbl_color = QtWidgets.QLabel(self.da_group)
        self.da_lbl_color.setGeometry(QtCore.QRect(50, 30, 38, 38))
        self.da_lbl_color.setMinimumSize(QtCore.QSize(38, 38))
        self.da_lbl_color.setMaximumSize(QtCore.QSize(38, 38))
        self.da_lbl_color.setAutoFillBackground(False)
        self.da_lbl_color.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid gray;")
        self.da_lbl_color.setText("")
        self.da_lbl_color.setObjectName("da_lbl_color")
        self.ml_group = QtWidgets.QGroupBox(self.centralwidget)
        self.ml_group.setGeometry(QtCore.QRect(10, 130, 391, 211))
        self.ml_group.setObjectName("ml_group")
        self.ml_lbl_color_h_min = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_color_h_min.setGeometry(QtCore.QRect(110, 110, 31, 16))
        self.ml_lbl_color_h_min.setObjectName("ml_lbl_color_h_min")
        self.ml_sld_color_s_min = QtWidgets.QSlider(self.ml_group)
        self.ml_sld_color_s_min.setGeometry(QtCore.QRect(40, 130, 161, 22))
        self.ml_sld_color_s_min.setMinimum(0)
        self.ml_sld_color_s_min.setMaximum(255)
        self.ml_sld_color_s_min.setPageStep(1)
        self.ml_sld_color_s_min.setSliderPosition(11)
        self.ml_sld_color_s_min.setTracking(False)
        self.ml_sld_color_s_min.setOrientation(QtCore.Qt.Horizontal)
        self.ml_sld_color_s_min.setObjectName("ml_sld_color_s_min")
        self.ml_sld_color_v_min = QtWidgets.QSlider(self.ml_group)
        self.ml_sld_color_v_min.setGeometry(QtCore.QRect(40, 170, 161, 22))
        self.ml_sld_color_v_min.setMinimum(0)
        self.ml_sld_color_v_min.setMaximum(255)
        self.ml_sld_color_v_min.setPageStep(1)
        self.ml_sld_color_v_min.setSliderPosition(11)
        self.ml_sld_color_v_min.setTracking(False)
        self.ml_sld_color_v_min.setOrientation(QtCore.Qt.Horizontal)
        self.ml_sld_color_v_min.setObjectName("ml_sld_color_v_min")
        self.ml_sld_color_s_max = QtWidgets.QSlider(self.ml_group)
        self.ml_sld_color_s_max.setGeometry(QtCore.QRect(220, 130, 161, 22))
        self.ml_sld_color_s_max.setMinimum(0)
        self.ml_sld_color_s_max.setMaximum(255)
        self.ml_sld_color_s_max.setPageStep(1)
        self.ml_sld_color_s_max.setSliderPosition(11)
        self.ml_sld_color_s_max.setTracking(False)
        self.ml_sld_color_s_max.setOrientation(QtCore.Qt.Horizontal)
        self.ml_sld_color_s_max.setObjectName("ml_sld_color_s_max")
        self.ml_sld_color_v_max = QtWidgets.QSlider(self.ml_group)
        self.ml_sld_color_v_max.setGeometry(QtCore.QRect(220, 170, 161, 22))
        self.ml_sld_color_v_max.setMinimum(0)
        self.ml_sld_color_v_max.setMaximum(255)
        self.ml_sld_color_v_max.setPageStep(1)
        self.ml_sld_color_v_max.setSliderPosition(11)
        self.ml_sld_color_v_max.setTracking(False)
        self.ml_sld_color_v_max.setOrientation(QtCore.Qt.Horizontal)
        self.ml_sld_color_v_max.setObjectName("ml_sld_color_v_max")
        self.ml_lbl_color_h_max = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_color_h_max.setGeometry(QtCore.QRect(290, 110, 31, 16))
        self.ml_lbl_color_h_max.setObjectName("ml_lbl_color_h_max")
        self.ml_lbl_color_s_min = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_color_s_min.setGeometry(QtCore.QRect(110, 150, 31, 16))
        self.ml_lbl_color_s_min.setObjectName("ml_lbl_color_s_min")
        self.ml_lbl_s = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_s.setGeometry(QtCore.QRect(10, 130, 31, 16))
        self.ml_lbl_s.setObjectName("ml_lbl_s")
        self.ml_lbl_v = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_v.setGeometry(QtCore.QRect(10, 170, 31, 16))
        self.ml_lbl_v.setObjectName("ml_lbl_v")
        self.ml_lbl_h = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_h.setGeometry(QtCore.QRect(10, 90, 31, 16))
        self.ml_lbl_h.setObjectName("ml_lbl_h")
        self.ml_sld_color_h_min = QtWidgets.QSlider(self.ml_group)
        self.ml_sld_color_h_min.setGeometry(QtCore.QRect(40, 90, 161, 22))
        self.ml_sld_color_h_min.setMinimum(0)
        self.ml_sld_color_h_min.setMaximum(179)
        self.ml_sld_color_h_min.setPageStep(1)
        self.ml_sld_color_h_min.setSliderPosition(90)
        self.ml_sld_color_h_min.setTracking(False)
        self.ml_sld_color_h_min.setOrientation(QtCore.Qt.Horizontal)
        self.ml_sld_color_h_min.setObjectName("ml_sld_color_h_min")
        self.ml_sld_color_h_max = QtWidgets.QSlider(self.ml_group)
        self.ml_sld_color_h_max.setGeometry(QtCore.QRect(220, 90, 161, 22))
        self.ml_sld_color_h_max.setMinimum(0)
        self.ml_sld_color_h_max.setMaximum(179)
        self.ml_sld_color_h_max.setPageStep(1)
        self.ml_sld_color_h_max.setSliderPosition(90)
        self.ml_sld_color_h_max.setTracking(False)
        self.ml_sld_color_h_max.setOrientation(QtCore.Qt.Horizontal)
        self.ml_sld_color_h_max.setObjectName("ml_sld_color_h_max")
        self.ml_lbl_color_v_min = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_color_v_min.setGeometry(QtCore.QRect(110, 190, 31, 16))
        self.ml_lbl_color_v_min.setObjectName("ml_lbl_color_v_min")
        self.ml_lbl_color_s_max = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_color_s_max.setGeometry(QtCore.QRect(290, 150, 31, 16))
        self.ml_lbl_color_s_max.setObjectName("ml_lbl_color_s_max")
        self.ml_btn_color = QtWidgets.QPushButton(self.ml_group)
        self.ml_btn_color.setGeometry(QtCore.QRect(10, 20, 40, 40))
        self.ml_btn_color.setMinimumSize(QtCore.QSize(40, 40))
        self.ml_btn_color.setMaximumSize(QtCore.QSize(40, 40))
        self.ml_btn_color.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.ml_btn_color.setText("")
        self.ml_btn_color.setIcon(icon4)
        self.ml_btn_color.setIconSize(QtCore.QSize(32, 32))
        self.ml_btn_color.setObjectName("ml_btn_color")
        self.ml_lbl_color = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_color.setGeometry(QtCore.QRect(50, 20, 38, 38))
        self.ml_lbl_color.setMinimumSize(QtCore.QSize(38, 38))
        self.ml_lbl_color.setMaximumSize(QtCore.QSize(38, 38))
        self.ml_lbl_color.setAutoFillBackground(False)
        self.ml_lbl_color.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid gray;")
        self.ml_lbl_color.setText("")
        self.ml_lbl_color.setObjectName("ml_lbl_color")
        self.ml_btn_view = QtWidgets.QPushButton(self.ml_group)
        self.ml_btn_view.setGeometry(QtCore.QRect(260, 20, 40, 40))
        self.ml_btn_view.setMinimumSize(QtCore.QSize(40, 40))
        self.ml_btn_view.setMaximumSize(QtCore.QSize(40, 40))
        self.ml_btn_view.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.ml_btn_view.setText("")
        self.ml_btn_view.setIcon(icon2)
        self.ml_btn_view.setIconSize(QtCore.QSize(32, 32))
        self.ml_btn_view.setObjectName("ml_btn_view")
        self.ml_btn_clear = QtWidgets.QPushButton(self.ml_group)
        self.ml_btn_clear.setGeometry(QtCore.QRect(300, 20, 40, 40))
        self.ml_btn_clear.setMinimumSize(QtCore.QSize(40, 40))
        self.ml_btn_clear.setMaximumSize(QtCore.QSize(40, 40))
        self.ml_btn_clear.setText("")
        self.ml_btn_clear.setIcon(icon)
        self.ml_btn_clear.setIconSize(QtCore.QSize(32, 32))
        self.ml_btn_clear.setObjectName("ml_btn_clear")
        self.ml_lbl_min = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_min.setGeometry(QtCore.QRect(40, 70, 31, 16))
        self.ml_lbl_min.setObjectName("ml_lbl_min")
        self.ml_lbl_max = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_max.setGeometry(QtCore.QRect(220, 70, 31, 16))
        self.ml_lbl_max.setObjectName("ml_lbl_max")
        self.ml_btn_delete = QtWidgets.QPushButton(self.ml_group)
        self.ml_btn_delete.setGeometry(QtCore.QRect(340, 20, 40, 40))
        self.ml_btn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.ml_btn_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.ml_btn_delete.setText("")
        self.ml_btn_delete.setIcon(icon3)
        self.ml_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.ml_btn_delete.setObjectName("ml_btn_delete")
        self.ml_lbl_color_v_max = QtWidgets.QLabel(self.ml_group)
        self.ml_lbl_color_v_max.setGeometry(QtCore.QRect(290, 190, 31, 16))
        self.ml_lbl_color_v_max.setObjectName("ml_lbl_color_v_max")
        self.tl_group = QtWidgets.QGroupBox(self.centralwidget)
        self.tl_group.setGeometry(QtCore.QRect(10, 360, 391, 81))
        self.tl_group.setObjectName("tl_group")
        self.tl_btn_clear = QtWidgets.QPushButton(self.tl_group)
        self.tl_btn_clear.setGeometry(QtCore.QRect(300, 30, 40, 40))
        self.tl_btn_clear.setMinimumSize(QtCore.QSize(40, 40))
        self.tl_btn_clear.setMaximumSize(QtCore.QSize(40, 40))
        self.tl_btn_clear.setText("")
        self.tl_btn_clear.setIcon(icon)
        self.tl_btn_clear.setIconSize(QtCore.QSize(32, 32))
        self.tl_btn_clear.setObjectName("tl_btn_clear")
        self.tl_btn_lines = QtWidgets.QPushButton(self.tl_group)
        self.tl_btn_lines.setGeometry(QtCore.QRect(10, 30, 40, 40))
        self.tl_btn_lines.setMinimumSize(QtCore.QSize(40, 40))
        self.tl_btn_lines.setMaximumSize(QtCore.QSize(40, 40))
        self.tl_btn_lines.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.tl_btn_lines.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/lineas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tl_btn_lines.setIcon(icon5)
        self.tl_btn_lines.setIconSize(QtCore.QSize(32, 32))
        self.tl_btn_lines.setObjectName("tl_btn_lines")
        self.tl_btn_eraser = QtWidgets.QPushButton(self.tl_group)
        self.tl_btn_eraser.setGeometry(QtCore.QRect(50, 30, 40, 40))
        self.tl_btn_eraser.setMinimumSize(QtCore.QSize(40, 40))
        self.tl_btn_eraser.setMaximumSize(QtCore.QSize(40, 40))
        self.tl_btn_eraser.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.tl_btn_eraser.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/borrador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tl_btn_eraser.setIcon(icon6)
        self.tl_btn_eraser.setIconSize(QtCore.QSize(36, 36))
        self.tl_btn_eraser.setObjectName("tl_btn_eraser")
        self.tl_btn_color = QtWidgets.QPushButton(self.tl_group)
        self.tl_btn_color.setGeometry(QtCore.QRect(90, 30, 40, 40))
        self.tl_btn_color.setMinimumSize(QtCore.QSize(40, 40))
        self.tl_btn_color.setMaximumSize(QtCore.QSize(40, 40))
        self.tl_btn_color.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.tl_btn_color.setText("")
        self.tl_btn_color.setIcon(icon4)
        self.tl_btn_color.setIconSize(QtCore.QSize(32, 32))
        self.tl_btn_color.setObjectName("tl_btn_color")
        self.tl_btn_view = QtWidgets.QPushButton(self.tl_group)
        self.tl_btn_view.setGeometry(QtCore.QRect(260, 30, 40, 40))
        self.tl_btn_view.setMinimumSize(QtCore.QSize(40, 40))
        self.tl_btn_view.setMaximumSize(QtCore.QSize(40, 40))
        self.tl_btn_view.setText("")
        self.tl_btn_view.setIcon(icon2)
        self.tl_btn_view.setIconSize(QtCore.QSize(32, 32))
        self.tl_btn_view.setObjectName("tl_btn_view")
        self.tl_lbl_color = QtWidgets.QLabel(self.tl_group)
        self.tl_lbl_color.setGeometry(QtCore.QRect(130, 30, 38, 38))
        self.tl_lbl_color.setMinimumSize(QtCore.QSize(38, 38))
        self.tl_lbl_color.setMaximumSize(QtCore.QSize(38, 38))
        self.tl_lbl_color.setAutoFillBackground(False)
        self.tl_lbl_color.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid gray;")
        self.tl_lbl_color.setText("")
        self.tl_lbl_color.setObjectName("tl_lbl_color")
        self.tl_sld_tickness = QtWidgets.QSlider(self.tl_group)
        self.tl_sld_tickness.setGeometry(QtCore.QRect(180, 30, 16, 31))
        self.tl_sld_tickness.setOrientation(QtCore.Qt.Vertical)
        self.tl_sld_tickness.setObjectName("tl_sld_tickness")
        self.tl_lbl_tickness = QtWidgets.QLabel(self.tl_group)
        self.tl_lbl_tickness.setGeometry(QtCore.QRect(210, 40, 31, 16))
        self.tl_lbl_tickness.setObjectName("tl_lbl_tickness")
        self.tl_btn_delete = QtWidgets.QPushButton(self.tl_group)
        self.tl_btn_delete.setGeometry(QtCore.QRect(340, 30, 40, 40))
        self.tl_btn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.tl_btn_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.tl_btn_delete.setText("")
        self.tl_btn_delete.setIcon(icon3)
        self.tl_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.tl_btn_delete.setObjectName("tl_btn_delete")
        self.tp_group = QtWidgets.QGroupBox(self.centralwidget)
        self.tp_group.setGeometry(QtCore.QRect(10, 550, 391, 131))
        self.tp_group.setObjectName("tp_group")
        self.tp_btn_clear = QtWidgets.QPushButton(self.tp_group)
        self.tp_btn_clear.setGeometry(QtCore.QRect(300, 30, 40, 40))
        self.tp_btn_clear.setMinimumSize(QtCore.QSize(40, 40))
        self.tp_btn_clear.setMaximumSize(QtCore.QSize(40, 40))
        self.tp_btn_clear.setText("")
        self.tp_btn_clear.setIcon(icon)
        self.tp_btn_clear.setIconSize(QtCore.QSize(32, 32))
        self.tp_btn_clear.setObjectName("tp_btn_clear")
        self.tp_btn_start = QtWidgets.QPushButton(self.tp_group)
        self.tp_btn_start.setGeometry(QtCore.QRect(220, 30, 40, 40))
        self.tp_btn_start.setMinimumSize(QtCore.QSize(40, 40))
        self.tp_btn_start.setMaximumSize(QtCore.QSize(40, 40))
        self.tp_btn_start.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.tp_btn_start.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/iniciar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tp_btn_start.setIcon(icon7)
        self.tp_btn_start.setIconSize(QtCore.QSize(36, 36))
        self.tp_btn_start.setObjectName("tp_btn_start")
        self.tp_btn_view = QtWidgets.QPushButton(self.tp_group)
        self.tp_btn_view.setGeometry(QtCore.QRect(260, 30, 40, 40))
        self.tp_btn_view.setMinimumSize(QtCore.QSize(40, 40))
        self.tp_btn_view.setMaximumSize(QtCore.QSize(40, 40))
        self.tp_btn_view.setText("")
        self.tp_btn_view.setIcon(icon2)
        self.tp_btn_view.setIconSize(QtCore.QSize(32, 32))
        self.tp_btn_view.setObjectName("tp_btn_view")
        self.tp_btn_delete = QtWidgets.QPushButton(self.tp_group)
        self.tp_btn_delete.setGeometry(QtCore.QRect(340, 30, 40, 40))
        self.tp_btn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.tp_btn_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.tp_btn_delete.setText("")
        self.tp_btn_delete.setIcon(icon3)
        self.tp_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.tp_btn_delete.setObjectName("tp_btn_delete")
        self.tp_sb_v_lines = QtWidgets.QSpinBox(self.tp_group)
        self.tp_sb_v_lines.setGeometry(QtCore.QRect(80, 40, 42, 20))
        self.tp_sb_v_lines.setMinimum(1)
        self.tp_sb_v_lines.setMaximum(40)
        self.tp_sb_v_lines.setProperty("value", 20)
        self.tp_sb_v_lines.setObjectName("tp_sb_v_lines")
        self.tp_sb_h_lines = QtWidgets.QSpinBox(self.tp_group)
        self.tp_sb_h_lines.setGeometry(QtCore.QRect(20, 40, 42, 20))
        self.tp_sb_h_lines.setMinimum(1)
        self.tp_sb_h_lines.setMaximum(40)
        self.tp_sb_h_lines.setProperty("value", 15)
        self.tp_sb_h_lines.setObjectName("tp_sb_h_lines")
        self.tp_lbl_h_lines = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_h_lines.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.tp_lbl_h_lines.setObjectName("tp_lbl_h_lines")
        self.tp_lbl_v_lines = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_v_lines.setGeometry(QtCore.QRect(70, 40, 31, 16))
        self.tp_lbl_v_lines.setObjectName("tp_lbl_v_lines")
        self.tp_lbl_lines = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_lines.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.tp_lbl_lines.setObjectName("tp_lbl_lines")
        self.tp_sb_h_degrees = QtWidgets.QSpinBox(self.tp_group)
        self.tp_sb_h_degrees.setGeometry(QtCore.QRect(20, 100, 42, 20))
        self.tp_sb_h_degrees.setMinimum(1)
        self.tp_sb_h_degrees.setMaximum(45)
        self.tp_sb_h_degrees.setProperty("value", 5)
        self.tp_sb_h_degrees.setObjectName("tp_sb_h_degrees")
        self.tp_lbl_v_degrees = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_v_degrees.setGeometry(QtCore.QRect(70, 100, 31, 16))
        self.tp_lbl_v_degrees.setObjectName("tp_lbl_v_degrees")
        self.tp_lbl_degrees = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_degrees.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.tp_lbl_degrees.setObjectName("tp_lbl_degrees")
        self.tp_sb_v_degrees = QtWidgets.QSpinBox(self.tp_group)
        self.tp_sb_v_degrees.setGeometry(QtCore.QRect(80, 100, 42, 20))
        self.tp_sb_v_degrees.setMinimum(1)
        self.tp_sb_v_degrees.setMaximum(45)
        self.tp_sb_v_degrees.setProperty("value", 25)
        self.tp_sb_v_degrees.setObjectName("tp_sb_v_degrees")
        self.tp_lbl_h_degrees = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_h_degrees.setGeometry(QtCore.QRect(10, 100, 31, 16))
        self.tp_lbl_h_degrees.setObjectName("tp_lbl_h_degrees")
        self.tp_sb_w_size = QtWidgets.QSpinBox(self.tp_group)
        self.tp_sb_w_size.setGeometry(QtCore.QRect(310, 100, 51, 20))
        self.tp_sb_w_size.setMinimum(100)
        self.tp_sb_w_size.setMaximum(1920)
        self.tp_sb_w_size.setProperty("value", 1200)
        self.tp_sb_w_size.setObjectName("tp_sb_w_size")
        self.tp_sb_h_size = QtWidgets.QSpinBox(self.tp_group)
        self.tp_sb_h_size.setGeometry(QtCore.QRect(229, 100, 51, 20))
        self.tp_sb_h_size.setMinimum(100)
        self.tp_sb_h_size.setMaximum(1080)
        self.tp_sb_h_size.setProperty("value", 500)
        self.tp_sb_h_size.setObjectName("tp_sb_h_size")
        self.tp_lbl_size = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_size.setGeometry(QtCore.QRect(219, 80, 111, 16))
        self.tp_lbl_size.setObjectName("tp_lbl_size")
        self.tp_lbl_w_size = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_w_size.setGeometry(QtCore.QRect(289, 100, 31, 16))
        self.tp_lbl_w_size.setObjectName("tp_lbl_w_size")
        self.tp_lbl_h_size = QtWidgets.QLabel(self.tp_group)
        self.tp_lbl_h_size.setGeometry(QtCore.QRect(219, 100, 31, 16))
        self.tp_lbl_h_size.setObjectName("tp_lbl_h_size")
        self.ce_group = QtWidgets.QGroupBox(self.centralwidget)
        self.ce_group.setGeometry(QtCore.QRect(10, 690, 391, 81))
        self.ce_group.setObjectName("ce_group")
        self.ce_btn_clear = QtWidgets.QPushButton(self.ce_group)
        self.ce_btn_clear.setGeometry(QtCore.QRect(300, 30, 40, 40))
        self.ce_btn_clear.setMinimumSize(QtCore.QSize(40, 40))
        self.ce_btn_clear.setMaximumSize(QtCore.QSize(40, 40))
        self.ce_btn_clear.setText("")
        self.ce_btn_clear.setIcon(icon)
        self.ce_btn_clear.setIconSize(QtCore.QSize(32, 32))
        self.ce_btn_clear.setObjectName("ce_btn_clear")
        self.ce_btn_view = QtWidgets.QPushButton(self.ce_group)
        self.ce_btn_view.setGeometry(QtCore.QRect(260, 30, 40, 40))
        self.ce_btn_view.setMinimumSize(QtCore.QSize(40, 40))
        self.ce_btn_view.setMaximumSize(QtCore.QSize(40, 40))
        self.ce_btn_view.setText("")
        self.ce_btn_view.setIcon(icon2)
        self.ce_btn_view.setIconSize(QtCore.QSize(32, 32))
        self.ce_btn_view.setObjectName("ce_btn_view")
        self.ce_btn_delete = QtWidgets.QPushButton(self.ce_group)
        self.ce_btn_delete.setGeometry(QtCore.QRect(340, 30, 40, 40))
        self.ce_btn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.ce_btn_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.ce_btn_delete.setText("")
        self.ce_btn_delete.setIcon(icon3)
        self.ce_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.ce_btn_delete.setObjectName("ce_btn_delete")
        self.ce_btn_start = QtWidgets.QPushButton(self.ce_group)
        self.ce_btn_start.setGeometry(QtCore.QRect(10, 30, 40, 40))
        self.ce_btn_start.setMinimumSize(QtCore.QSize(40, 40))
        self.ce_btn_start.setMaximumSize(QtCore.QSize(40, 40))
        self.ce_btn_start.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.ce_btn_start.setText("")
        self.ce_btn_start.setIcon(icon7)
        self.ce_btn_start.setIconSize(QtCore.QSize(36, 36))
        self.ce_btn_start.setObjectName("ce_btn_start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbr_load_image.setTitle(_translate("MainWindow", "Carga de imagen"))
        self.btn_load_image.setText(_translate("MainWindow", "Cargar imagen"))
        self.lbl_load_image.setText(_translate("MainWindow", "..."))
        self.da_group.setTitle(_translate("MainWindow", "Delimitación de areas"))
        self.da_btn_clear.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.da_btn_coordinates.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar coordenadas</p></body></html>"))
        self.da_btn_view.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ver imagen</p></body></html>"))
        self.da_btn_delete.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.da_btn_color.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.da_btn_color.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.ml_group.setTitle(_translate("MainWindow", "Mascara de lineas"))
        self.ml_lbl_color_h_min.setText(_translate("MainWindow", "11 %"))
        self.ml_lbl_color_h_max.setText(_translate("MainWindow", "11 %"))
        self.ml_lbl_color_s_min.setText(_translate("MainWindow", "11 %"))
        self.ml_lbl_s.setText(_translate("MainWindow", "S"))
        self.ml_lbl_v.setText(_translate("MainWindow", "V"))
        self.ml_lbl_h.setText(_translate("MainWindow", "H"))
        self.ml_lbl_color_v_min.setText(_translate("MainWindow", "11 %"))
        self.ml_lbl_color_s_max.setText(_translate("MainWindow", "11 %"))
        self.ml_btn_color.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.ml_btn_color.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.ml_btn_view.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.ml_btn_view.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.ml_btn_clear.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.ml_lbl_min.setText(_translate("MainWindow", "Min"))
        self.ml_lbl_max.setText(_translate("MainWindow", "Max"))
        self.ml_btn_delete.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.ml_lbl_color_v_max.setText(_translate("MainWindow", "11 %"))
        self.tl_group.setTitle(_translate("MainWindow", "Transformacion libre"))
        self.tl_btn_clear.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.tl_btn_lines.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.tl_btn_lines.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.tl_btn_eraser.setToolTip(_translate("MainWindow", "<html><head/><body><p>Borrador</p></body></html>"))
        self.tl_btn_color.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.tl_btn_color.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.tl_btn_view.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ver imagen</p></body></html>"))
        self.tl_lbl_tickness.setText(_translate("MainWindow", "11 %"))
        self.tl_btn_delete.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.tp_group.setTitle(_translate("MainWindow", "Transformación de perspectiva"))
        self.tp_btn_clear.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.tp_btn_start.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar coordenadas</p></body></html>"))
        self.tp_btn_view.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ver imagen</p></body></html>"))
        self.tp_btn_delete.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.tp_lbl_h_lines.setText(_translate("MainWindow", "H"))
        self.tp_lbl_v_lines.setText(_translate("MainWindow", "V"))
        self.tp_lbl_lines.setText(_translate("MainWindow", "Tolerancias entre lineas"))
        self.tp_lbl_v_degrees.setText(_translate("MainWindow", "V"))
        self.tp_lbl_degrees.setText(_translate("MainWindow", "Tolerancias en grados"))
        self.tp_lbl_h_degrees.setText(_translate("MainWindow", "H"))
        self.tp_lbl_size.setText(_translate("MainWindow", "Tamaño perspectiva"))
        self.tp_lbl_w_size.setText(_translate("MainWindow", "W"))
        self.tp_lbl_h_size.setText(_translate("MainWindow", "H"))
        self.ce_group.setTitle(_translate("MainWindow", "Configuración de espacios"))
        self.ce_btn_clear.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.ce_btn_view.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ver imagen</p></body></html>"))
        self.ce_btn_delete.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.ce_btn_start.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar coordenadas</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
